[package]
name = "my-todo-list"
version = "1.0.0"
authors = []

[addresses]
NotionOnAptos='b687713cade5116f731f73cb4c210740ce0849304f0a0dae10a37375b7ffde68'
Std = "0x1"
aptos_std = "0x1"


[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
