[package]
name = "nft-marketplace"
version = "1.0.0"
authors = []

[addresses]
mint_nft='b687713cade5116f731f73cb4c210740ce0849304f0a0dae10a37375b7ffde68'

[dev-addresses]

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token/"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
